networks:
  revisor-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  # Frontend - Interfaz de Usuario
  revisor-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revisor-web-prod
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PYTHON_API_URL=http://172.30.0.10:8000
    env_file:
      - ./thesis-reviewer/.env.local
    depends_on:
      - revisor-api
    networks:
      - revisor-net
    restart: always

  # Backend - Motor Experto de Python
  revisor-api:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: revisor-api-prod
    ports:
      - "8005:8000"
    volumes:
      - ./backend-python/tmp_uploads:/app/tmp_uploads
      - ./backend-python/services/auditors:/app/services/auditors
    env_file:
      - ./thesis-reviewer/.env.local
    networks:
      revisor-net:
        ipv4_address: 172.30.0.10
    restart: always
