services:
  # Frontend - Interfaz de Usuario
  revisor-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revisor-web-prod
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - PYTHON_API_URL=http://revisor-api:8000
    depends_on:
      - revisor-api
    restart: always

  # Backend - Motor Experto de Python
  revisor-api:
    build:
      context: ./backend-python
      dockerfile: Dockerfile
    container_name: revisor-api-prod
    ports:
      - "8005:8000"
    volumes:
      - ./backend-python/tmp_uploads:/app/tmp_uploads
    restart: always

volumes:
  ocr_data:
