services:
  thesis-reviewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thesis-reviewer-app
    ports:
      - "3001:3000"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: revisor-network
